### ISSUE TITLE
Server not receiving packets

### ISSUE THREAD

**Issue by davedoesdev** [deitch/multicast-test#1]
I can see the packets exactly as you say using `tcpdump`.
Do you have any pointers as to why the server is not receiving them on my machine?
Thanks

**Comment by davedoesdev** [comment]
This fixed it for me:

```diff
diff --git a/server.c b/server.c
index d42de4c..c586f56 100644
--- a/server.c
+++ b/server.c
@@ -35,7 +35,7 @@ int main(int argc, char* argv[]) {
        
   bzero((char *)&addr, sizeof(addr));
   addr.sin_family = AF_INET;
-  addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);
+  addr.sin_addr.s_addr = htonl(INADDR_ANY);
   addr.sin_port = htons(atoi(server_port));
        addr_size = sizeof(addr);
```

I got this from https://stackoverflow.com/a/12863865

**Comment by deitch** [comment]
This seems odd to me. Granted, the point here is to show the problem with *sending*, not *receiving*, so it doesn't matter all that much, but even so. 

I'll try it a bit later.

**Comment by deitch** [comment]
Turns out to be a timing issue. Fixing `run.sh`
